spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/db_shiro2
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 1234
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.offcn.springbootshiro.beans